name: 'List findings'
description: 'List the found findings of a fuzzing run'
inputs:
  ci_fuzz_api_token:
    description: 'CI Fuzz Access Token'
    required: true
  github_token:
    description: 'GitHub Access Token'
    required: true
  dashboard_address:
    description: "URL of Code-Intelligence's fuzzing dashboard"
    required: true
  project:
    description: 'Name of the project'
    required: true
  owner:
    description: 'owner'
    required: true
  repository:
    description: 'repository'
    required: true
  name:
    description: 'name of the check'
    required: true
  test_collection_run:
    description: 'specific campaign run'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
