name: "Build and Instrument"
description: "Builds the Test Collection for fuzzing, instruments and starts it"
inputs:
  ci_fuzz_api_token:
    description: "Token generated in the web app, used for authenticating with the fuzzing server"
    required: false
  cognito_user:
    description: "Cognito credentials to authenticate with Code-Intelligence's fuzzing server"
    required: false
  cognito_password:
    description: "Cognito credentials to authenticate with Code-Intelligence's fuzzing server"
    required: false
  project:
    description: "Name of the project"
    required: false
  test_collection:
    description: "Name of the Test Collection in the specified project"
    required: false
  fuzzing_artifact:
    description: "Fuzzing artifact path. Used when building the fuzzing artifact in a github workflow."
    required: false
  checkout_directory:
    description: "Directory of the repository checkout. Relative to the github workspace. Defaults to the github workspace."
    required: false
    default: ""
  report_email:
    description: "E-mail to receive crash reports"
    required: false
  fuzzing_server_address:
    description: "URL of Code-Intelligence's gRPC server for fuzzing"
    required: false
    default: "grpc-api.code-intelligence.com:443"
  git_reference:
    description: "Git reference used when pulling code from the repository to be fuzzed"
    required: false
  application_base_url:
    description: "The base URL of the application under test. Only relevant for web application fuzzing."
    required: false
runs:
  using: "docker"
  image: "docker://cifuzz/github-action:3.10.0"
  entrypoint: "start_fuzzing.sh"
