name: "Build and Instrument"
description: "Builds the Test Collection for fuzzing, instruments and starts it"
inputs:
  cognito_user:
    description: "Cognito credentials to authenticate with Code-Intelligence's fuzzing server"
    required: true
  cognito_password:
    description: "Cognito credentials to authenticate with Code-Intelligence's fuzzing server"
    required: true
  project:
    description: "Name of the project"
    required: true
  test_collection:
    description: "Name of the Test Collection in the specified project"
    required: true
  report_email:
    description: "E-mail to receive crash reports"
    required: false
  fuzzing_server_address:
    description: "URL of Code-Intelligence's gRPC server for fuzzing"
    required: false
    default: "grpc-api.code-intelligence.com:443"
  git_reference:
    description: "Git reference used when pulling code from the repository to be fuzzed"
runs:
  using: "docker"
  image: "docker://gcr.io/code-intelligence/cictl:2.16.0"
  entrypoint: "start_fuzzing.sh"
