name: "Monitor Fuzzing"
description: "Monitor a Test Collection Run until it crashes or reaches the timeout"
inputs:
  cognito_user:
    description: "Cognito credentials to authenticate with Code-Intelligence's fuzzing server"
    required: true
  cognito_password:
    description: "Cognito credentials to authenticate with Code-Intelligence's fuzzing server"
    required: true
  project:
    description: "Name of the project"
    required: true
  test_collection:
    description: "Name of the Test Collection in the specified project"
    required: true
  fuzzing_server_address:
    description: "URL of Code-Intelligence's gRPC server for fuzzing"
    required: false
    default: "grpc-api.code-intelligence.com:443"
  dashboard_address:
    description: "URL of Code-Intelligence's fuzzing dashboard"
    required: false
    default: "https://app.code-intelligence.com"
  github_token:
    description: "GitHub token used by the GitHub API to create a comment in a pull request with the coverage information"
  pull_request_number:
    description: "Number of the pull request where the comment with the coverage information will be created"
  owner:
    description: "Owner of the repository that contains the pull request"
  repository:
    description: "Repository that contains the pull request"
  commit:
    description: "Commit SHA used when forming the URL to the files"
runs:
  using: "docker"
  image: "docker://cifuzz/cictl:2.15-alpha"
  entrypoint: "report_coverage.sh"