name: "Fuzzing"
description: "Monitor a Test Collection Run until it crashes or reaches the timeout"
inputs:
  ci_fuzz_api_token:
    description: "Token generated in the web app, used for authenticating with the fuzzing server"
    required: false
  cognito_user:
    description: "Cognito credentials to authenticate with Code-Intelligence's fuzzing server"
    required: false
  cognito_password:
    description: "Cognito credentials to authenticate with Code-Intelligence's fuzzing server"
    required: false
  project:
    description: "Name of the project"
    required: true
  test_collection_run:
    description: "Name of the Test Collection Run"
    required: true
  timeout:
    description: "Timeout (in seconds) to monitor the fuzzing. If no crash was found when it times out, the action is considered successful."
    required: false
    default: "300"
  findings_type:
    description: "Comma separated types of findings to monitor. Accepted values: UNKNOWN_ERROR, COMPILATION_ERROR, CRASH, WARNING, RUNTIME_ERROR."
    required: false
    default: "CRASH"
  fuzzing_server_address:
    description: "URL of Code-Intelligence's gRPC server for fuzzing"
    required: false
    default: "grpc-api.code-intelligence.com:443"
  dashboard_address:
    description: "URL of Code-Intelligence's fuzzing dashboard"
    required: false
    default: "https://app.code-intelligence.com"
  github_token:
    description: "GitHub token used by the GitHub API to create a comment in a pull request with a link to the finding"
    required: false
  pull_request_number:
    description: "Number of the pull request where the comment with the finding link will be created"
    required: false
  owner:
    description: "Owner of the repository that contains the pull request"
    required: false
  repository:
    description: "Repository that contains the pull request"
    required: false
runs:
  using: "docker"
  image: "docker://cifuzz/github-action:3.10.0"
  entrypoint: "monitor_fuzzing.sh"
