name: "Save Fuzz Test Results"
description: "Save findings and coverage of a CI Fuzz workflow run"
inputs:
  ci_fuzz_api_token:
    description: "Token generated in the web app, used for authenticating with the fuzzing server"
    required: true
  project:
    description: "Name of the project"
    required: true
  test_collection_run:
    description: "Name of the Test Collection Run"
    required: true
  fuzzing_server_address:
    description: "URL of Code-Intelligence's gRPC server for fuzzing"
    required: false
    default: "api.code-intelligence.com:6773"
  dashboard_address:
    description: "URL of Code-Intelligence's fuzzing dashboard"
    required: false
    default: "https://app.code-intelligence.com"

runs:
  using: "docker"
  image: "docker://cifuzz/github-action:3.12.0"
  entrypoint: "export_results.sh"
